[package]
name = "easy32"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
# for bench comparison: https://github.com/andreasots/base32
base32 = "0.4.0"
criterion = "0.5.1"
# for bench comparison: https://github.com/archer884/crockford
crockford = "1.2.1"

[[bench]]
name = "comparisons"
harness = false
